### ISSUE TITLE
cannot access local variable 'files' where it is not associated with a value

### ISSUE THREAD

**Issue by Mercy0310** [xtxt19931207/emby-alist#4]
<img width="997" alt="屏幕截图 2023-12-05 212743" src="https://github.com/xtxt19931207/emby-alist/assets/88916091/9d08a8ee-a3fe-4c09-ba13-7a18df5785c6">

请问一下这个是为什么。。

**Comment by suxss** [comment]
这是因为在 `main.py` 第 20 行 webdav 连接失败导致变量 `files` 没有初始化, 而在第 30 行直接引用了未初始化的变量 `files`
https://github.com/xtxt19931207/emby-alist/blob/004e60efc8abbb02055e2da2c6cddade49ce721a/main.py#L17-L35
这段代码应该优化一下, 但是你这里的主要问题还是在于 webdav 连接失败, 检查一下变量 `webdav_url` 是否正确(#1), 尝试更换网络,   尝试挂梯子等
